name: Java sdk CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build jar
        timeout-minutes: 30
        shell: bash
        run: |
          echo "build jar"
          git submodule update --init
          mvn clean versions:set -DnewVersion=2.2.12
          mvn clean install -Dmaven.test.skip=true -Dgpg.skip

      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs-java-sdk-ci-test
          path: |
            tests/test/target/surefire-reports
            tests/test/target/allure-results 
